## Import libraries

In [1]:
import numpy as np

## Perform Matrix Operation

In [2]:
# Define matrices A and B
A = np.array([[2, -1], [0, 3]])
B = np.array([[1, 2], [-3, 4]])

# Perform matrix operations
A_plus_B = A + B
A_times_B = np.dot(A, B)  # Matrix multiplication
three_A_minus_two_B = 3 * A - 2 * B

print("A + B:\n", A_plus_B)
print("A * B:\n", A_times_B)
print("3A - 2B:\n", three_A_minus_two_B)

A + B:
 [[ 3  1]
 [-3  7]]
A * B:
 [[ 5  0]
 [-9 12]]
3A - 2B:
 [[ 4 -7]
 [ 6  1]]


In [3]:
# Define matrix A
A = np.array([[2, -1], [0, 3]])

# Compute the determinant of A
det_A = np.linalg.det(A)

# Check if A is invertible and compute its inverse if possible
if det_A != 0:
    A_inverse = np.linalg.inv(A)
else:
    A_inverse = "A is not invertible"

print("Determinant of A:", det_A)
print("Inverse of A:\n", A_inverse)

Determinant of A: 6.0
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


## Eigen values and Prediction

In [4]:
# Define matrix C
C = np.array([[4, 1], [-2, 1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(C)

# Define feature matrix X and price vector y
X = np.array([[4, 1.5, 100], [6, 2.0, 150]])
y = np.array([20, 30])

# Compute β using the pseudoinverse
beta = np.linalg.pinv(X) @ y

# Define the feature vector for car 3
x3 = np.array([8, 3.0, 200])

# Predict the price of car 3
price_car3 = x3 @ beta

print("Eigenvalues of C:\n", eigenvalues)
print("Eigenvectors of C:\n", eigenvectors)
print("Beta coefficients:\n", beta)
print("Predicted price of Car 3:", price_car3)

Eigenvalues of C:
 [3. 2.]
Eigenvectors of C:
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]
Beta coefficients:
 [ 7.98722045e-03 -1.06581410e-14  1.99680511e-01]
Predicted price of Car 3: 39.99999999999997
